Build fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,28 +38,28 @@ jobs:
           docker build . -t $IMAGE_NAME
           docker push $IMAGE_NAME
 
-#  test:
-#    name: Test
-#    runs-on: ubuntu-latest
-#
-#    needs: build
-#
-#    steps:
-#      - name: Checkout code
-#        uses: actions/checkout@v2
-#
-#      - name: Login to Docker registry
-#        run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD
-#
-#      - name: Pull Docker image
-#        run: |
-#          IMAGE_NAME=$REGISTRY_LOGIN/$REPO_NAME:${{ github.sha }}
-#          docker pull $IMAGE_NAME
-#          docker run $IMAGE_NAME php artisan test || (echo "Tests failed" && docker rmi $IMAGE_NAME && exit 1)
+  test:
+    name: Test
+    runs-on: ubuntu-latest
+
+    needs: build
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Login to Docker registry
+        run: echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASSWORD
+
+      - name: Pull Docker image
+        run: |
+          IMAGE_NAME=$REGISTRY_LOGIN/$REPO_NAME:${{ github.sha }}
+          docker pull $IMAGE_NAME
+          docker run $IMAGE_NAME php artisan test || (echo "Tests failed" && docker rmi $IMAGE_NAME && exit 1)
 
   deploy:
     name: Deploy
-#    needs: test
+    needs: test
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -73,7 +73,7 @@ jobs:
           key: ${{ secrets.SERVER_KEY }}
           port: 22
           script: |
-            IMAGE_NAME=${{ vars.REGISTRY_LOGIN }}/${{ vars.REGISTRY_LOGIN }}:${{ github.sha }}
+            IMAGE_NAME=${{ vars.REGISTRY_LOGIN }}/${{ vars.REPO_NAME }}:${{ github.sha }}
             mkdir -p ${{ vars.COMPOSE_PATH }}
             rm ${{ vars.COMPOSE_PATH }}/docker-compose.yml
             printf "%s" "${{ vars.DOCKER_COMPOSE }}" >> ${{ vars.COMPOSE_PATH }}/docker-compose.yml
